//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;

    public partial class detalle_prestamos
    {
        public System.Guid dtp_prestamo { get; set; }
        public System.Guid dtp_libro { get; set; }
        public int dtp_cantidad { get; set; }
        public System.DateTime dtp_fecha_fin { get; set; }
        public Nullable<System.DateTime> dtp_fecha_dev { get; set; }
    
        public virtual libros libros { get; set; }
        public virtual prestamos prestamos { get; set; }
    }
}
