//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libros()
        {
            this.DetallePrestamos = new HashSet<DetallePrestamos>();
        }
    
        public int lib_codigo { get; set; }
        public string lib_nombre { get; set; }
        public int lib_num_pag { get; set; }
        public string lib_autor { get; set; }
        public string lib_editorial { get; set; }
        public int lib_area { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePrestamos> DetallePrestamos { get; set; }
        public virtual Areas Areas { get; set; }
    }
}
