//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class LibraryContext : DbContext
    {
        public LibraryContext()
            : base("name=LibraryContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<areas> Areas { get; set; }
        public virtual DbSet<detalle_prestamos> DetallePrestamos { get; set; }
        public virtual DbSet<libros> Libros { get; set; }
        public virtual DbSet<prestamos> Prestamos { get; set; }
        public virtual DbSet<sanciones> Sanciones { get; set; }
        public virtual DbSet<usuarios> Usuarios { get; set; }
    }
}
