//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanciones
    {
        public System.Guid san_codigo { get; set; }
        public int san_prestamo { get; set; }
        public int san_dias_sancion { get; set; }
        public System.DateTime san_fecha_inicio { get; set; }
        public System.DateTime san_fecha_fin { get; set; }
    
        public virtual Prestamos Prestamos { get; set; }
    }
}
